import { requireDriver } from "@/lib/driver-session";
import { db } from "@/lib/db";
import { DriverForm } from "@/components/admin/driver-form";
import type { DriverInput } from "@/lib/validation";
export default async function ProfilePage({ searchParams }: { searchParams: Promise<{ guardado?: string }> }) {
  const actor = await requireDriver();
  const [driver, services] = await Promise.all([db().driver.findUniqueOrThrow({ where: { id: actor.driverId }, include: { photos: { where: { category: "VEHICLE" }, orderBy: [{ position: "asc" }, { id: "asc" }], take: 1, select: { id: true } }, services: { select: { id: true } }, vehicles: { orderBy: [{ active: "desc" }, { createdAt: "asc" }], take: 1 } } }), db().service.findMany({ where: { active: true }, select: { id: true, name: true }, orderBy: { name: "asc" } })]);
  const vehicle = driver.vehicles.find(v => v.active);
  const initial: DriverInput = { name: driver.name, slug: driver.slug, phone: driver.phone || "", whatsapp: driver.whatsapp || "", email: driver.email || "", location: driver.location || "", experience: driver.experience, description: driver.description || "", photoUrl: driver.photoUrl || "", languages: Array.isArray(driver.languages) ? driver.languages.filter((v): v is string => typeof v === "string") : [], active: driver.active, verified: driver.verified, serviceIds: driver.services.map(s => s.id), vehicle: vehicle ? { brand: vehicle.brand, model: vehicle.model, year: vehicle.year, color: vehicle.color || "", plate: vehicle.plate || "", passengers: vehicle.passengers, description: vehicle.description || "", photoUrl: vehicle.photoUrl || "" } : null };
  return <><div className="workspace-heading"><div><span className="eyebrow">TU MEJOR PRESENTACIÓN</span><h1>Mi perfil<span>.</span></h1><p>Mantén tus datos, servicios y vehículo al día. La publicación y verificación las gestiona tu administrador.</p></div></div>{(await searchParams).guardado === "1" && <p role="status" className="form-success">Tu perfil se guardó correctamente.</p>}<DriverForm key={driver.updatedAt.toISOString()} id={driver.id} initial={initial} services={services} mode="driver" vehicleCoverUrl={driver.photos[0] ? `/media/${driver.photos[0].id}` : undefined} /></>;
}
