"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
export function DriverAccessForm({ id, username, active = false }: { id: string; username?: string; active?: boolean }) {
  const router = useRouter(), [pending, setPending] = useState(false), [error, setError] = useState("");
  const [success, setSuccess] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const formElement = event.currentTarget, form = new FormData(formElement); setPending(true); setError(""); setSuccess(false);
    try { const response = await fetch(`/api/admin/conductores/${id}/acceso`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username: form.get("username"), password: form.get("password"), active: form.get("active") === "on" }) }); const result = await response.json(); if (!response.ok) { setError(result.error); return; } (formElement.elements.namedItem("password") as HTMLInputElement).value = ""; setSuccess(true); router.refresh(); }
    catch { setError("No pudimos guardar el acceso. Intenta de nuevo."); } finally { setPending(false); }
  }
  return <><form className="access-form" onSubmit={submit}><label>Usuario del conductor<input name="username" required minLength={3} maxLength={64} defaultValue={username} autoComplete="off" autoCapitalize="none" /></label><label>{username ? "Nueva contraseña temporal" : "Contraseña temporal"}<input name="password" type="password" required minLength={12} maxLength={72} autoComplete="new-password" /></label><label className="consent-label"><input name="active" type="checkbox" defaultChecked={username ? active : true} />Permitir acceso al conductor</label><p className="calendar-help">El conductor deberá cambiar esta contraseña al entrar. Guardar invalida sus sesiones y la conexión anterior de calendario. Comunícale el acceso por tu canal habitual.</p><button className="button button-primary" disabled={pending}>{pending ? "Guardando…" : username ? "Restablecer acceso" : "Crear acceso"}</button></form>{username && <button className="text-link" disabled={pending} onClick={async () => { setPending(true); setError(""); try { const response = await fetch(`/api/admin/conductores/${id}/acceso`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ active: !active }) }); if (!response.ok) throw new Error(); router.refresh(); } catch { setError("No se pudo cambiar el estado del acceso."); } finally { setPending(false); } }}>{active ? "Desactivar acceso" : "Reactivar acceso"}</button>}{success && <p className="form-success" role="status">Acceso guardado. El conductor puede entrar en /login-conductor.</p>}{error && <p role="alert" className="form-error">{error}</p>}</>;
}
