import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { passengerBooking, passengerFeedUrl, passengerPath } from "@/lib/calendar-access";
import { authConfiguration } from "@/lib/security";
import { formatTripDate, statusLabels } from "@/lib/calendar";
import { AccountConnection } from "@/components/calendar/account-connection";
import { CalendarActions } from "@/components/booking/calendar-actions";
import { PrivateLink } from "@/components/booking/private-link";
export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Mi traslado | Driver Connect", description: "Consulta el estado de tu solicitud de traslado.", robots: { index: false, follow: false, noarchive: true }, referrer: "no-referrer" };
export default async function PassengerPage({ params }: { params: Promise<{ id: string; token: string }> }) {
  const { id, token } = await params, booking = await passengerBooking(id, token); if (!booking) notFound();
  const text = { PENDING: "Recibimos tu solicitud. Tu conductor debe contactarte para acordar disponibilidad y precio. Todavía no es una reserva confirmada.", CONFIRMED: "Tu conductor confirmó este traslado. Aquí puedes consultar los detalles y añadirlo a tu calendario.", CANCELLED: "Este traslado fue cancelado. Contacta con tu conductor si necesitas coordinar otro viaje.", REJECTED: "El conductor no pudo aceptar esta solicitud. Puedes contactarlo para consultar otra alternativa." };
  return <main className="private-booking"><header className="private-booking-header"><span className="footer-brand">Driver Connect<span>.</span></span><span className="calendar-help">Tu enlace privado de viaje</span></header><div className="workspace-heading"><div><span className="eyebrow">CADA VIAJE, BIEN COORDINADO</span><h1>Tu próximo destino<span>.</span></h1><p>{booking.driver.name} · {booking.serviceName}</p></div><span className={`booking-status ${booking.status.toLowerCase()}`}>{statusLabels[booking.status]}</span></div><div className="detail-grid"><section className="detail-card"><h2>{booking.status === "CONFIRMED" ? "Nos vemos pronto." : "El estado de tu viaje."}</h2><p>{text[booking.status]}</p><dl className="detail-data"><div><dt>Fecha y hora de recogida</dt><dd>{formatTripDate(booking.startsAt)}<br /><small>Hora de Panamá · UTC−5</small></dd></div><div><dt>Pasajeros</dt><dd>{booking.passengers}</dd></div><div><dt>Recogida</dt><dd>{booking.pickup}</dd></div><div><dt>Destino</dt><dd>{booking.destination}</dd></div></dl><PrivateLink url={`${authConfiguration().origin}${passengerPath(booking)}`} refresh /><p className="calendar-help">Conserva este enlace: permite consultar el estado y los detalles de este viaje. No lo publiques.</p>{booking.driver.active && <Link className="text-link" href={`/conductor/${booking.driver.slug}`}>Contactar con mi conductor →</Link>}</section><aside className="detail-card"><h2>En tu calendario.</h2><AccountConnection audience={{ kind: "passenger", id, token }} /><details className="calendar-details"><summary>Otras opciones de calendario</summary><CalendarActions trip={booking} feedUrl={passengerFeedUrl(booking)} /></details></aside></div></main>;
}
