import Image from "next/image";
import type { PublicDriver } from "@/lib/public-driver";
import { Icon } from "./icon";
import { ShareProfile } from "./share-profile";

export function PublicDriverProfile({ driver }: { driver: PublicDriver }) {
  const vehicle = driver.vehicles[0];
  const initials = driver.name.split(/\s+/).slice(0, 2).map((name) => name[0]).join("");
  const contactUrl = `/conductor/${driver.slug}/contacto`;
  const whatsappUrl = driver.whatsapp ? `https://wa.me/${driver.whatsapp.replace(/\D/g, "")}` : null;
  return <><a className="skip-link" href="#perfil">Saltar al perfil</a><div className="site-shell">
    <header className="site-header"><a href="#perfil" className="brand" aria-label="Driver Connect"><span className="brand-symbol">dc<span>.</span></span><span className="brand-word">DRIVER<br /><strong>CONNECT</strong></span></a><nav aria-label="Perfil del conductor">{driver.services.length > 0 && <a href="#servicios">Servicios</a>}{vehicle && <a href="#vehiculo">Vehículo</a>}<a className="nav-contact" href="#contacto">Contacto <Icon name="arrow" /></a></nav></header>
    <main><section className="profile-hero" id="perfil" aria-labelledby="driver-name"><div className="profile-copy"><div className="profile-intro">{driver.photoUrl ? <Image className="avatar-photo" src={driver.photoUrl} alt={driver.name} width={66} height={66} unoptimized referrerPolicy="no-referrer" /> : <span className="avatar">{initials}</span>}<div><span className="eyebrow">TU CONDUCTOR PRIVADO</span>{driver.location && <span className="location"><Icon name="pin" />{driver.location}</span>}</div></div><h1 id="driver-name">{driver.name}</h1>{driver.verified && <p className="verified-driver"><Icon name="check" />Verificado por administración</p>}{driver.description && <p className="profile-description">{driver.description}</p>}<div className="profile-details"><span><Icon name="clock" />{driver.experience} {driver.experience === 1 ? "año" : "años"} de experiencia</span>{driver.languages.length > 0 && <span><Icon name="globe" />{driver.languages.join(" · ")}</span>}</div><div className="hero-actions">{whatsappUrl ? <a className="button button-primary" href={whatsappUrl} target="_blank" rel="noopener noreferrer"><Icon name="message" />WhatsApp</a> : <a className="button button-primary" href={contactUrl} download><Icon name="download" />Guardar contacto</a>}<ShareProfile path={`/conductor/${driver.slug}`} title={`${driver.name} · Driver Connect`} /></div>{whatsappUrl && <a className="public-save-link" href={contactUrl} download>Guardar contacto <Icon name="download" /></a>}</div><div className={`hero-photo ${vehicle?.photoUrl ? "" : "profile-cover"}`}>{vehicle?.photoUrl ? <Image src={vehicle.photoUrl} alt={`${vehicle.brand} ${vehicle.model}`} fill sizes="(max-width: 760px) 100vw, 50vw" unoptimized referrerPolicy="no-referrer" /> : <span className="cover-monogram" aria-hidden="true">dc.</span>}<div className="photo-caption"><span className="eyebrow">DRIVER CONNECT</span><strong>{vehicle ? `${vehicle.brand} ${vehicle.model}` : "Tu conductor privado."}</strong>{driver.location && <span className="photo-coordinate">{driver.location}</span>}</div></div></section>
    {driver.services.length > 0 && <section className="services-section" id="servicios" aria-labelledby="services-title"><div className="section-heading"><div><span className="eyebrow">SERVICIOS</span><h2 id="services-title">Para cada <em>destino.</em></h2></div></div><div className="services-grid">{driver.services.map((service, index) => <article className="service-card" key={service.name}><div className="service-top"><span className="service-icon"><Icon name={service.icon || "compass"} /></span><span>{String(index + 1).padStart(2, "0")}</span></div><h3>{service.name}</h3>{service.description && <p>{service.description}</p>}</article>)}</div></section>}
    {vehicle && <section className="vehicle-section" id="vehiculo" aria-labelledby="vehicle-title"><div><span className="eyebrow">A BORDO</span><h2 id="vehicle-title">El espacio también<br /><em>hace la diferencia.</em></h2>{vehicle.description && <p>{vehicle.description}</p>}</div><div className="vehicle-specs"><h3>{vehicle.brand} {vehicle.model}</h3><span className="vehicle-type">{vehicle.year}{vehicle.color ? ` · ${vehicle.color}` : ""}</span><div className="specs-grid"><span><Icon name="user" /><strong>{vehicle.passengers} pasajeros</strong>Capacidad de servicio</span></div></div></section>}
    <section className="contact-section" id="contacto" aria-labelledby="contact-title"><div><span className="eyebrow">SIGAMOS EN CONTACTO</span><h2 id="contact-title">Tu próximo viaje,<br /><em>a una conversación.</em></h2></div><div className="contact-options">{whatsappUrl && <a className="contact-option" href={whatsappUrl} target="_blank" rel="noopener noreferrer"><Icon name="message" /><span><strong>WhatsApp</strong><small>{driver.whatsapp}</small></span><Icon name="arrow" /></a>}{driver.phone && <a className="contact-option" href={`tel:${driver.phone}`}><Icon name="user" /><span><strong>Llamar</strong><small>{driver.phone}</small></span><Icon name="arrow" /></a>}{driver.email && <a className="contact-option" href={`mailto:${driver.email}`}><Icon name="mail" /><span><strong>Correo electrónico</strong><small>{driver.email}</small></span><Icon name="arrow" /></a>}<a href={contactUrl} download className="contact-download">Guardar contacto<Icon name="download" /></a></div></section></main>
    <footer className="site-footer"><a href="#perfil" className="footer-brand">Driver Connect<span>.</span></a><span>Una conexión. Más posibilidades.</span></footer>
  </div></>;
}
