import Image from "next/image";
import Link from "next/link";
import type { PublicDriver } from "@/lib/public-driver";
import { Icon } from "./icon";
import { ShareProfile } from "./share-profile";
export function PublicDriverProfile({ driver, demo = false }: { driver: PublicDriver; demo?: boolean }) {
  const vehicle = driver.vehicles[0], vehicleName = vehicle ? `${vehicle.brand} ${vehicle.model}`.trim() : "Tu próximo destino.";
  const initials = driver.name.split(/\s+/).slice(0, 2).map(name => name[0]).join("");
  const contact = `/conductor/${driver.slug}/contacto`, reserve = `/conductor/${driver.slug}/reservar`;
  const whatsapp = driver.whatsapp ? `https://wa.me/${driver.whatsapp.replace(/\D/g, "")}` : null;
  const hasAction = demo || driver.bookingEnabled || whatsapp;
  return <div className={`driver-public ${hasAction ? "with-mobile-actions" : ""}`}><a className="skip-link" href="#perfil">Saltar al perfil</a>{demo && <div className="demo-bar"><span className="demo-dot" />Perfil ficticio de muestra <span className="demo-separator">·</span> Datos y vehículo ilustrativos<Link href="/demo/agenda">Conoce la nueva agenda ↗</Link></div>}
    <div className="public-container"><header className="public-header"><a href="#perfil" className="brand"><span className="brand-symbol">dc<span>.</span></span><span className="brand-word">DRIVER<br /><strong>CONNECT</strong></span></a><nav aria-label="Perfil del conductor">{driver.services.length > 0 && <a href="#servicios">Servicios</a>}{vehicle && <a href="#vehiculo">Vehículo</a>}<a href="#contacto">Contacto</a><Link className="professional-access" href="/login-conductor">Acceso conductor ↗</Link></nav></header>
    <main><section className="public-hero" id="perfil" aria-labelledby="driver-name"><div className="public-identity"><div className="profile-intro">{driver.photoUrl ? <Image className="avatar-photo" src={driver.photoUrl} alt={driver.name} width={66} height={66} unoptimized referrerPolicy="no-referrer" /> : <span className="avatar">{initials}</span>}<div><span className="eyebrow">TU CONDUCTOR PRIVADO</span>{driver.location && <span className="location"><Icon name="pin" />{driver.location}</span>}</div></div><h1 id="driver-name">{driver.name}<span>.</span></h1><p className="public-tagline">Cada viaje,<br /><em>a tu ritmo.</em></p>{driver.verified && <p className="verified-driver"><Icon name="shield" />Verificado por administración</p>}{driver.description && <p className="profile-description">{driver.description}</p>}<div className="public-facts"><span><strong>{driver.experience}<small> años</small></strong><span>de experiencia</span></span>{driver.languages.length > 0 && <span><strong><Icon name="globe" /></strong><span>{driver.languages.join(" · ")}</span></span>}</div><div className="public-primary-actions">{driver.bookingEnabled && <Link className="button button-primary" href={reserve}>Solicitar un traslado <Icon name="arrow" /></Link>}{whatsapp && <a className="button button-secondary" href={whatsapp} target="_blank" rel="noopener noreferrer"><Icon name="message" />WhatsApp</a>}{demo && <Link className="button button-primary" href="/demo/agenda">Conoce el espacio del conductor <Icon name="arrow" /></Link>}{!driver.bookingEnabled && !whatsapp && !demo && <a className="button button-primary" href={contact} download><Icon name="download" />Guardar contacto</a>}</div>{driver.bookingEnabled && <p className="action-note">Disponibilidad y precio sujetos a confirmación.</p>}{demo && <p className="action-note">Las reservas y los canales reales están deshabilitados en esta muestra.</p>}<div className="public-utility"><a href={contact} download><Icon name="download" />Guardar contacto</a><ShareProfile path={`/conductor/${driver.slug}`} title={`${driver.name} · Driver Connect${demo ? " (muestra)" : ""}`} /></div></div><div className="public-visual">{vehicle?.photoUrl ? <Image src={vehicle.photoUrl} alt={demo ? "Imagen ilustrativa de un SUV en la costa de Panamá" : vehicleName} fill sizes="(max-width: 760px) 90vw, 48vw" unoptimized={!demo} preload referrerPolicy="no-referrer" /> : <div className="public-monogram" aria-hidden="true">dc<span>.</span></div>}<span className="visual-top-label">{demo ? "IMAGEN ILUSTRATIVA" : "DRIVER CONNECT"}</span><div className="visual-caption"><span>EL TRAYECTO TAMBIÉN CUENTA</span><h2>{vehicleName}</h2><div>{vehicle && <span><Icon name="user" />Hasta {vehicle.passengers} pasajeros</span>}{driver.location && <span>{driver.location}</span>}</div></div></div></section>
    {driver.services.length > 0 && <section className="public-services" id="servicios"><div className="public-section-heading"><div><span className="eyebrow">01 / SERVICIOS</span><h2>Un servicio para<br /><em>cada destino.</em></h2></div><p>Conoce las opciones de tu conductor<br />y coordina los detalles de tu viaje.</p></div><div className="public-service-grid">{driver.services.map((service, index) => <article key={service.name}><div className="public-service-top"><Icon name={service.icon || "compass"} /><span>{String(index + 1).padStart(2, "0")}</span></div><h3>{service.name}</h3>{service.description && <p>{service.description}</p>}{driver.bookingEnabled && <Link href={`${reserve}?servicio=${encodeURIComponent(service.name)}`} className="text-link">Solicitar este servicio <Icon name="arrow" /></Link>}{!driver.bookingEnabled && whatsapp && <a className="text-link" href={`${whatsapp}?text=${encodeURIComponent(`Hola, me interesa ${service.name}. Quisiera consultar disponibilidad y precio.`)}`} target="_blank" rel="noopener noreferrer">Consultar servicio <Icon name="arrow" /></a>}</article>)}</div></section>}
    {vehicle && <section className="public-vehicle" id="vehiculo"><div><span className="eyebrow">02 / A BORDO</span><h2>El espacio también<br /><em>hace la diferencia.</em></h2>{vehicle.description && <p>{vehicle.description}</p>}</div><article><div className="vehicle-card-heading"><Icon name="compass" /><span>VEHÍCULO PRINCIPAL</span></div><h3>{vehicleName}</h3><dl>{[["Capacidad", `${vehicle.passengers} pasajeros`], ["Año", String(vehicle.year)], ["Color", vehicle.color]].filter(([, value]) => Boolean(value)).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></article></section>}
    <section className="public-contact" id="contacto"><div><span className="eyebrow">03 / SIGAMOS EN CONTACTO</span><h2>Tu próximo viaje,<br /><em>a una conversación.</em></h2>{driver.bookingEnabled && <Link className="button public-reserve-button" href={reserve}>Solicitar mi traslado <Icon name="arrow" /></Link>}{demo && <p>Esta es una demostración de Driver Connect.<br />Los canales de contacto reales no están habilitados.</p>}</div><div className="public-contact-links">{whatsapp && <a href={whatsapp} target="_blank" rel="noopener noreferrer"><span className="public-channel-icon"><Icon name="message" /></span><span><strong>WhatsApp</strong><small>{driver.whatsapp}</small></span><Icon name="arrow" /></a>}{driver.phone && <a href={`tel:${driver.phone}`}><span className="public-channel-icon"><Icon name="user" /></span><span><strong>Llamar</strong><small>{driver.phone}</small></span><Icon name="arrow" /></a>}{driver.email && <a href={`mailto:${driver.email}`}><span className="public-channel-icon"><Icon name="mail" /></span><span><strong>Correo electrónico</strong><small>{driver.email}</small></span><Icon name="arrow" /></a>}<a href={contact} download><span className="public-channel-icon"><Icon name="download" /></span><span><strong>Guardar contacto</strong><small>{demo ? "Tarjeta de muestra, sin teléfono ni correo" : "La información de tu conductor, a mano"}</small></span><Icon name="arrow" /></a></div></section></main>
    <footer className="public-footer"><a className="footer-brand" href="#perfil">Driver Connect<span>.</span></a><span>Una conexión. Más posibilidades.</span><Link href="/login-conductor">Espacio del conductor ↗</Link></footer></div>
    {hasAction && <nav className="public-mobile-actions" aria-label="Contacto rápido">{driver.bookingEnabled && <Link className="button button-primary" href={reserve}>Solicitar traslado <Icon name="arrow" /></Link>}{whatsapp && <a className="button button-secondary" href={whatsapp} target="_blank" rel="noopener noreferrer"><Icon name="message" />WhatsApp</a>}{demo && <Link className="button button-primary" href="/demo/agenda">Conoce la nueva agenda <Icon name="arrow" /></Link>}</nav>}
  </div>;
}
