"use client";
import Image from "next/image";
import { useId, useRef, useState } from "react";
export type GalleryPhoto = { id: string; category: "TRIP" | "VEHICLE"; caption: string; width: number; height: number };
export function PhotoCarousel({ photos }: { photos: GalleryPhoto[] }) {
  const [category, setCategory] = useState("ALL"), [current, setCurrent] = useState(0), track = useRef<HTMLDivElement>(null), id = useId();
  const visible = photos.filter(p => category === "ALL" || p.category === category);
  if (!photos.length) return null;
  function move(index: number) { const element = track.current?.children[index] as HTMLElement | undefined; if (element && track.current) track.current.scrollTo({ left: element.offsetLeft, behavior: matchMedia("(prefers-reduced-motion: reduce)").matches ? "instant" : "smooth" }); }
  return <section className="photo-gallery" id="galeria" aria-label="Fotos del conductor"><div className="public-section-heading"><div><span className="eyebrow">A TRAVÉS DEL CAMINO</span><h2>Viajes que cuentan.<br /><em>Un vehículo que conoces.</em></h2></div><div className="gallery-filters" aria-label="Filtrar fotografías">{[["ALL", "Todas"], ["TRIP", "Viajes"], ["VEHICLE", "Vehículo"]].filter(([key]) => key === "ALL" || photos.some(p => p.category === key)).map(([key, label]) => <button type="button" key={key} aria-pressed={category === key} onClick={() => { setCategory(key); setCurrent(0); track.current?.scrollTo({ left: 0 }); }}>{label}</button>)}</div></div><div className="gallery-track" id={id} ref={track} tabIndex={0} aria-label="Fotografías; desliza o usa los botones para recorrerlas" onKeyDown={event => { if (event.key === "ArrowRight" || event.key === "ArrowLeft") { event.preventDefault(); move(Math.max(0, Math.min(visible.length - 1, current + (event.key === "ArrowRight" ? 1 : -1)))); } }} onScroll={() => { const container = track.current; if (!container) return; let nearest = 0, distance = Infinity; Array.from(container.children).forEach((child, index) => { const next = Math.abs((child as HTMLElement).offsetLeft - container.scrollLeft); if (next < distance) { nearest = index; distance = next; } }); setCurrent(nearest); }}>{visible.map((photo, index) => <figure className="gallery-slide" key={photo.id} role="group" aria-roledescription="diapositiva" aria-label={`${index + 1} de ${visible.length}`}><Image src={`/media/${photo.id}`} alt={photo.caption} width={photo.width} height={photo.height} unoptimized sizes="(max-width: 760px) 85vw, 60vw" /><figcaption><span>{photo.category === "TRIP" ? "UN MOMENTO DEL VIAJE" : "A BORDO"}</span><p>{photo.caption}</p></figcaption></figure>)}</div><div className="gallery-navigation"><span aria-live="polite" aria-atomic="true">{current + 1} / {visible.length}</span><div><button className="button button-secondary" type="button" aria-label="Foto anterior" aria-controls={id} disabled={current === 0} onClick={() => move(current - 1)}>←</button><button className="button button-secondary" type="button" aria-label="Foto siguiente" aria-controls={id} disabled={current >= visible.length - 1} onClick={() => move(current + 1)}>→</button></div></div></section>;
}
