import Link from "next/link";
import { Icon } from "../icon";
import { formatTripDate, localDateTime, monthRange, statusLabels, type TripStatus } from "@/lib/calendar";
export type AgendaTrip = { id: string; customerName: string; serviceName: string; pickup: string; destination: string; startsAt: Date; endsAt: Date; status: TripStatus; passengers: number };
export function AgendaView({ trips, month, pending, total, day, pendingOnly = false, demo = false }: { trips: AgendaTrip[]; month: string; pending: number; total: number; day?: string; pendingOnly?: boolean; demo?: boolean }) {
  const range = monthRange(month), monthName = new Intl.DateTimeFormat("es-PA", { month: "long", year: "numeric", timeZone: "America/Panama" }).format(range.start);
  const startWeek = (range.start.getUTCDay() + 6) % 7, days = Math.round((range.end.getTime() - range.start.getTime()) / 86400_000);
  const route = demo ? "/demo/agenda" : "/panel/agenda";
  const href = (m: string, d?: string) => `${route}?mes=${m}${d ? `&dia=${d}` : ""}`;
  const visible = day && !pendingOnly ? trips.filter(t => localDateTime(t.startsAt).slice(0, 10) === day) : trips;
  const confirmed = trips.filter(t => t.status === "CONFIRMED").length;
  return <>
    {demo && <p className="demo-notice">Vista de muestra · Personas y viajes ficticios. No se ha creado ninguna reserva.</p>}
    <div className="workspace-heading"><div><span className="eyebrow">TODO LISTO PARA EL SIGUIENTE DESTINO</span><h1>Tu agenda<span>.</span></h1><p>Organiza cada viaje. Dale espacio a lo que viene.</p></div><Link className="button button-primary" href={demo ? "/login-conductor" : "/panel/agenda/nuevo"}>+ Nuevo viaje</Link></div>
    <div className="trip-stats"><Link href={`${route}?mes=${month}&estado=PENDING`}><span className="stat-icon amber"><Icon name="message" /></span><div><span>Por responder</span><strong>{pending.toString().padStart(2, "0")}</strong></div><Icon name="arrow" /></Link><div><span className="stat-icon green"><Icon name="check" /></span><div><span>Confirmados en esta vista</span><strong>{confirmed.toString().padStart(2, "0")}</strong></div></div><Link href={demo ? "/login-conductor" : "/panel/calendario"}><span className="stat-icon blue"><Icon name="calendar" /></span><div><span>Siempre a mano</span><strong className="stat-text">Tu calendario</strong></div><Icon name="arrow" /></Link></div>
    <section className="agenda-board" aria-labelledby="calendar-title"><header className="agenda-board-header"><div><span className="eyebrow">PLANIFICA TU MES</span><h2 id="calendar-title">{monthName}</h2></div><div className="calendar-controls"><Link className="icon-button" href={href(range.previous)} aria-label="Mes anterior">←</Link><Link href={href(localDateTime(new Date()).slice(0, 7))}>Hoy</Link><Link className="icon-button" href={href(range.next)} aria-label="Mes siguiente">→</Link></div></header><div className="calendar-week" aria-hidden="true">{["Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"].map(d => <span key={d}>{d}</span>)}</div><div className="month-grid">{Array.from({ length: Math.ceil((days + startWeek) / 7) * 7 }, (_, index) => {
      const number = index - startWeek + 1;
      if (number < 1 || number > days) return <div key={index} className="calendar-blank" />;
      const date = `${month}-${String(number).padStart(2, "0")}`, events = trips.filter(t => localDateTime(t.startsAt).slice(0, 10) === date && !["CANCELLED", "REJECTED"].includes(t.status));
      return <Link key={index} href={href(month, date)} className={`calendar-day ${date === localDateTime(new Date()).slice(0, 10) ? "today" : ""} ${day === date ? "selected" : ""}`} aria-label={`${date}: ${events.length} viajes`} aria-current={day === date ? "date" : undefined}><span>{number}</span><div className="day-events">{events.slice(0, 2).map(t => <small key={t.id} className={`day-event ${t.status.toLowerCase()}`}><i />{localDateTime(t.startsAt).slice(11)} <span>{t.serviceName}</span></small>)}{events.length > 2 && <small className="event-extra">+{events.length - 2} más</small>}</div></Link>;
    })}</div><footer className="calendar-legend"><span><i className="legend-green" />Confirmado</span><span><i className="legend-amber" />Pendiente</span><span>Hora de Panamá · UTC−5</span></footer></section>
    <section className="trip-list-section"><div className="list-heading"><div><span className="eyebrow">CADA DETALLE CUENTA</span><h2>{pendingOnly ? "Solicitudes por responder" : day ? `Viajes del ${day.slice(8)}/${day.slice(5, 7)}` : "Viajes del mes"}</h2></div>{(day || pendingOnly) && <Link href={href(month)}>Ver todo el mes →</Link>}</div>{visible.length ? <div className="trip-cards">{visible.map(trip => <Link href={demo ? "/login-conductor" : `/panel/agenda/${trip.id}`} className="trip-card" key={trip.id}><div className="trip-time"><strong>{localDateTime(trip.startsAt).slice(11)}</strong><span>{formatTripDate(trip.startsAt).split(",")[0]}</span></div><div className="trip-main"><div><span className={`booking-status ${trip.status.toLowerCase()}`}>{statusLabels[trip.status]}</span><span className="trip-service">{trip.serviceName}</span></div><h3>{trip.pickup} <span>→</span> {trip.destination}</h3><p>{trip.customerName} <span>·</span> {trip.passengers} {trip.passengers === 1 ? "pasajero" : "pasajeros"}</p></div><span className="trip-open" aria-label="Ver detalles"><Icon name="arrow" /></span></Link>)}</div> : <div className="agenda-empty"><span className="stat-icon"><Icon name="calendar" /></span><h3>Espacio para tu próximo viaje.</h3><p>{pendingOnly ? "No tienes solicitudes pendientes." : "No hay viajes en esta selección."}</p><Link className="text-link" href={demo ? "/login-conductor" : "/panel/agenda/nuevo"}>Registrar un viaje →</Link></div>}{total > trips.length && <p className="muted">Se muestran {trips.length} de {total} viajes. Selecciona otro mes para consultar más registros.</p>}</section>
  </>;
}
