import Link from "next/link";
import { requireDriver } from "@/lib/driver-session";
import { db } from "@/lib/db";
import { formatTripDate, statusLabels } from "@/lib/calendar";
import { ShareProfile } from "@/components/share-profile";
import { Icon } from "@/components/icon";
export default async function PanelPage() {
  const actor = await requireDriver(), now = new Date();
  const [pending, confirmed, trips] = await Promise.all([db().booking.count({ where: { driverId: actor.driverId, status: "PENDING" } }), db().booking.count({ where: { driverId: actor.driverId, status: "CONFIRMED", endsAt: { gte: now } } }), db().booking.findMany({ where: { driverId: actor.driverId, status: { in: ["PENDING", "CONFIRMED"] }, endsAt: { gte: now } }, orderBy: { startsAt: "asc" }, take: 5 })]);
  return <><div className="workspace-heading"><div><span className="eyebrow">BIENVENIDO A TU ESPACIO</span><h1>Hola, {actor.name.split(" ")[0]}<span>.</span></h1><p>Un vistazo a lo que viene. Todo bajo control.</p></div><Link className="button button-primary" href="/panel/agenda/nuevo">+ Nuevo viaje</Link></div><div className="trip-stats"><Link href="/panel/agenda?estado=PENDING"><span className="stat-icon amber"><Icon name="message" /></span><div><span>Solicitudes por responder</span><strong>{pending}</strong></div><Icon name="arrow" /></Link><Link href="/panel/agenda"><span className="stat-icon green"><Icon name="check" /></span><div><span>Próximos viajes confirmados</span><strong>{confirmed}</strong></div><Icon name="arrow" /></Link><Link href="/panel/perfil"><span className="stat-icon blue"><Icon name="user" /></span><div><span>Tu perfil profesional</span><strong className="stat-text">{actor.published ? "Publicado" : "En borrador"}</strong></div><Icon name="arrow" /></Link></div><div className="detail-grid"><section className="detail-card"><div className="list-heading"><h2>Próximos destinos</h2><Link href="/panel/agenda">Ver agenda →</Link></div>{trips.length ? <ul className="driver-list">{trips.map(t => <li key={t.id}><div><strong>{t.pickup} → {t.destination}</strong><span>{formatTripDate(t.startsAt)} · {t.customerName}</span></div><span className={`booking-status ${t.status.toLowerCase()}`}>{statusLabels[t.status]}</span><Link href={`/panel/agenda/${t.id}`}>Ver →</Link></li>)}</ul> : <p>Tus próximos viajes aparecerán aquí. Puedes registrarlos o recibir solicitudes desde tu perfil.</p>}</section><aside><section className="reservation-intro"><span className="eyebrow">TU PRESENTACIÓN, SIEMPRE CONTIGO</span><h2>Una conexión.<br /><em>Más posibilidades.</em></h2><p>Tu perfil reúne tu presentación, servicios y contacto en una dirección que puedes compartir o grabar en tu tarjeta NFC.</p><div className="detail-actions"><ShareProfile path={`/conductor/${actor.slug}`} title={`${actor.name} · Driver Connect`} /></div></section><section className="detail-card"><h2>Tu agenda, en el móvil.</h2><p>Lleva tus viajes a Google Calendar o conecta Calendario de iPhone sin descargar archivos.</p><Link className="text-link" href="/panel/calendario">Conectar mi calendario →</Link></section></aside></div></>;
}
