import Link from "next/link";
import { notFound } from "next/navigation";
import { requireDriver } from "@/lib/driver-session";
import { db } from "@/lib/db";
import { formatTripDate, localDateTime, statusLabels } from "@/lib/calendar";
import { passengerFeedUrl, passengerPath } from "@/lib/calendar-access";
import { authConfiguration } from "@/lib/security";
import { CalendarActions } from "@/components/booking/calendar-actions";
import { BookingActions, RotatePassengerLink } from "@/components/booking/booking-actions";
import { PrivateLink } from "@/components/booking/private-link";
import { TripForm } from "@/components/booking/trip-form";
export default async function TripPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ editar?: string; guardado?: string }> }) {
  const actor = await requireDriver(), { id } = await params, query = await searchParams;
  const trip = await db().booking.findFirst({ where: { id, driverId: actor.driverId } });
  if (!trip) notFound();
  const editable = ["PENDING", "CONFIRMED"].includes(trip.status), edit = query.editar === "1" && editable;
  return <><div className="workspace-heading"><div><Link className="text-link" href={`/panel/agenda?mes=${localDateTime(trip.startsAt).slice(0, 7)}`}>← Volver a mi agenda</Link><h1>{edit ? "Editar viaje" : trip.serviceName}<span>.</span></h1><p>{formatTripDate(trip.startsAt)} · Hora de Panamá</p></div><span className={`booking-status ${trip.status.toLowerCase()}`}>{statusLabels[trip.status]}</span></div>{query.guardado === "1" && <p className="form-success" role="status">Viaje guardado correctamente.</p>}{edit ? <TripForm id={trip.id} version={trip.version} initial={{ serviceName: trip.serviceName, customerName: trip.customerName, phone: trip.phone, email: trip.email || "", pickup: trip.pickup, destination: trip.destination, startsAt: localDateTime(trip.startsAt), duration: Math.round((trip.endsAt.getTime() - trip.startsAt.getTime()) / 60_000), passengers: trip.passengers, notes: trip.notes || "" }} /> : <div className="detail-grid"><div><section className="detail-card"><h2>Detalles del traslado</h2><dl className="detail-data">{[["Recogida", trip.pickup], ["Destino", trip.destination], ["Pasajero", trip.customerName], ["Pasajeros", String(trip.passengers)], ["Teléfono", trip.phone], ["Correo", trip.email || "No indicado"], ["Fin estimado", formatTripDate(trip.endsAt)], ["Origen de la reserva", trip.source === "REQUEST" ? "Solicitud del perfil" : "Registro del conductor"]].map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}{trip.notes && <div className="full-width"><dt>Notas privadas</dt><dd>{trip.notes}</dd></div>}</dl>{trip.status === "PENDING" && <p className="calendar-help">Comprueba precio, hora y duración con el pasajero antes de confirmar. La duración inicial de una solicitud es de 60 minutos.</p>}<div className="detail-actions">{editable && <Link className="button button-secondary" href={`/panel/agenda/${id}?editar=1`}>Editar datos</Link>}<a className="button button-secondary" href={`tel:${trip.phone}`}>Llamar al pasajero</a></div><BookingActions id={id} status={trip.status} version={trip.version} /></section><section className="detail-card"><h2>Enlace para el pasajero</h2><p>El pasajero puede consultar el estado del viaje y conectarlo con su calendario. Copia este enlace para compartirlo con él.</p><PrivateLink key={trip.passengerVersion} url={`${authConfiguration().origin}${passengerPath(trip)}`} /><RotatePassengerLink id={trip.id} /><p className="calendar-help">No se envían avisos automáticamente. Comunica las confirmaciones y los cambios al pasajero por tu canal habitual.</p></section></div><aside className="detail-card"><h2>Llévalo a tu calendario.</h2><Link className="button button-primary" href="/panel/calendario">Sincronizar con mi teléfono</Link><details className="calendar-details"><summary>Otras opciones</summary><CalendarActions trip={trip} feedUrl={passengerFeedUrl(trip)} /></details><Link className="text-link" href="/panel/calendario">Conectar mi agenda completa →</Link></aside></div>}</>;
}
